[project]
name = "youtube2tiktok"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.1.0",
    "yt-dlp[default]>=2025.12.8",
]
